// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiBW1-Qh1cPObGVlJSRX9YQzaGVlc1ZMc',
    appId: '1:1058359163576:android:220a3835f3beb8da5c924d',
    messagingSenderId: '1058359163576',
    projectId: 'flutter-starter-template-99523',
    storageBucket: 'flutter-starter-template-99523.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEMvd9oGSOriFRWRj99wLM0F_ll0vZH7A',
    appId: '1:1058359163576:ios:1bc5a652eac421d25c924d',
    messagingSenderId: '1058359163576',
    projectId: 'flutter-starter-template-99523',
    storageBucket: 'flutter-starter-template-99523.appspot.com',
    androidClientId: '1058359163576-evdrhtgpq5mnqn39jlqcbsol5p17a6mt.apps.googleusercontent.com',
    iosClientId: '1058359163576-769mjlu5k0p76h95i16kvi576brmbs4l.apps.googleusercontent.com',
    iosBundleId: 'np.com.naxa.startertemplate',
  );

}